config/routes.rb
Rails.application.routes.draw do
  
  
  root "posts#index"


  devise_for :users
  resources :posts
  # allowing only create and destroy on resources
  resources :comments, only: [:create, :destroy]

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post


  # validating the presence/existence of user model object 
  # (instead of just user_id or post_id)
  # when a new comment is created
  validates :user, presence: true
  validates :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user

	# dependent: :destroy is tells rails to remove the
	# dependent (has many) objects when the parent object is destroyed
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  # dependent: :destroy is tells rails to remove the
  # dependent (has many) objects when the parent object is destroyed
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # these are callbacks

  # authenticate_user! is provided by devise
  before_action :authenticate_user!

  # set_comment sets the value of @comment from params
  before_action :set_comment, only: [:destroy]

  # authorize_user finds whether a user can perform the desired action
  before_action :authorize_user, only: [:destroy]


  def create
  	comment = Comment.new(comment_params)
  	comment.user = current_user
  	comment.save

  	return redirect_to post_path(comment.post_id)
  end

  def destroy
  	post = @comment.post
  	@comment.destroy

  	return redirect_to post_path(post.id)

  end

  private
  	def set_comment
      @comment = Comment.find(params[:id])
    end

	def authorize_user
	  if current_user != @comment.user
	    return redirect_to root_path
	  end
	  return true
	end

   def comment_params
      params.require(:comment).permit(:post_id, :content)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # authenticate_user! is provided by devise
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # set_comment sets the value of @comment from params
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  
  # authorize_user finds whether a user can perform the desired action
  before_action :authorize_user, only: [:edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    # add user to the new post in @post
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def authorize_user
      if current_user != @post.user
        return redirect_to root_path
      end
      return true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scaffoldproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav>
		<!-- displaying sign up, sign in & sign out links only when needed -->
		<ul style="list-style: none;">
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<% if !user_signed_in? %>
			<li>
				<%= link_to "Sign Up", new_user_registration_path %>
			</li>
			<li>
				<%= link_to "Sign In", new_user_session_path %>
			</li>
			<% else %>
			<li>
				<p>Hello <%= current_user.email %></p>
			</li>
			<li>
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
			</li>

			<% end %>
		</ul>
	</nav>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<!-- empty @post (user signed in)-->
<!-- edit existing @post (user_signed_in? && current_user == @post.user)-->
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <!-- replacing the above line to display only the signed in user's post -->
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>
        <td><%= link_to 'Show', post %></td>

        <!-- if we are displaying all the posts, then we can use the line below
        to show edit and update links only if the user is signed in -->
        <% if user_signed_in? && current_user == post.user %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<ul>
	<!-- display the comments for each post -->
	<% @post.comments.each do |comment| %>
	<li>
		<p>
			<%= comment.content %>
			 by <%= comment.user.email %>

			<% if user_signed_in? && current_user == comment.user %>
			<%= link_to "X", comment_path(comment.id), method: :delete %>

			<% end %>
		</p>
	</li>
	<% end %>
</ul>

<!-- a form for creating new comments for a post -->
<%= form_for @comment do |f| %>
	<%= f.hidden_field :post_id, value: @post.id %>
	<%= f.label :content, "Add Comment"%>
	<%= f.text_field :content %>
	<br>
	<%= f.submit %>
<% end %>

<% if user_signed_in? && current_user == @post.user %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>

<%= link_to 'Back', posts_path %>